# Generated by Django 4.2.2 on 2023-07-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_latitude_alter_place_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
