# Generated by Django 4.2.2 on 2023-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_order_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Порядок'),
        ),
    ]
