# Generated by Django 4.2.2 on 2023-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
